aws_project/usage/routes.py
from flask import Blueprint, render_template, request
from flask_pymongo import PyMongo
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from . import usage_bp

from flask_caching import Cache
from hashlib import md5

def make_cache_key():
    return md5(request.path.encode('utf-8')).hexdigest()

cache = Cache()

# Initialize cache with default settings
def init_cache(app):
    cache.init_app(app)

usage_bp = Blueprint('usage', __name__, template_folder='templates')

# Use the usage MongoDB instance
mongo_usage = PyMongo()

@usage_bp.record_once
def on_load(state):
    global mongo_usage
    mongo_usage.init_app(state.app, uri=state.app.config["MONGO_URI_USAGE"])

# Function to get date range
def get_date_range():
    min_date = datetime.utcnow().date()
    max_date = datetime(1970, 1, 1).date()  # start with a very old date

    for collection in mongo_usage.db.list_collection_names():
        data = list(mongo_usage.db[collection].find())
        for document in data:
            for year, months in document.items():
                if not year.isdigit():
                    continue
                for month, days in months.items():
                    for day in days.keys():
                        date = datetime(int(year), int(month), int(day)).date()
                        min_date = min(min_date, date)
                        max_date = max(max_date, date)

    return min_date, max_date


def get_usage_data(service):
    # Query the database for the specified service
    data = list(mongo_usage.db[service].find())

    # Initialize an empty dictionary to store the usage data
    usage_data = {}

    # Loop through the data and populate the usage_data dictionary
    for doc in data:
        for year, months in doc.items():
            if not year.isdigit():
                continue
            for month, days in months.items():
                for day, cost in days.items():
                    date = f"{year}-{month}-{day}"
                    usage_type = doc.get('UsageTypes')
                    if usage_type not in usage_data:
                        usage_data[usage_type] = {}
                    usage_data[usage_type][date] = float(cost)

    return usage_data


# Function to calculate weekly usage data
@cache.cached(timeout=86400, key_prefix=make_cache_key)  # Cache for 24 hours (adjust timeout as needed)
def calculate_weekly_data(service):
    # Query the database for the specified service
    data = list(mongo_usage.db[service].find())

    # Initialize weekly data dictionary
    weekly_data = {}

    min_date, max_date = get_date_range()
    # Calculate start and end dates for the past 8 weeks (including the current week)
    # end_date = max_date
    end_date = max_date - timedelta(days=(max_date.weekday() + 1) % 7)
    start_date = end_date - relativedelta(weeks=7)

    # Find the Monday of the start_date week
    start_date -= timedelta(days=start_date.weekday())

    # Iterate over each week within the selected date range
    current_date = start_date
    while current_date <= end_date:
        for doc in data:
            usage_type = doc.get('UsageTypes')
            if usage_type not in weekly_data:
                weekly_data[usage_type] = {}
            weekly_data[usage_type][current_date] = 0
            for year, months in doc.items():
                if not year.isdigit():
                    continue
                for month, days in months.items():
                    for day, cost in days.items():
                        date = datetime(int(year), int(month), int(day)).date()
                        if current_date <= date < current_date + timedelta(days=7):
                            weekly_data[usage_type][current_date] += cost
        # Move to next week
        current_date += timedelta(days=7)

    return weekly_data


# Function to calculate monthly usage data
@cache.cached(timeout=86400)  # Cache for 24 hours (adjust timeout as needed)
def calculate_monthly_data(service):
    # Query the database for the specified service
    data = list(mongo_usage.db[service].find())

    # Initialize monthly data dictionary
    monthly_data = {}

    # Fetch the date range
    min_date, max_date = get_date_range()

    # Calculate start and end dates for the past 8 months (including the current month)
    # end_date = max_date.replace(day=1)
    end_date = max_date.replace(day=1) - timedelta(days=1)
    start_date = end_date.replace(day=1) - relativedelta(months=7)

    # Iterate over each month within the selected date range
    current_date = start_date.replace(day=1)
    while current_date.replace(day=1) <= end_date.replace(day=1):
        for doc in data:
            usage_type = doc.get('UsageTypes')
            if usage_type not in monthly_data:
                monthly_data[usage_type] = {}
            monthly_data[usage_type][current_date.strftime('%B-%Y')] = 0
            for year, months in doc.items():
                if not year.isdigit():
                    continue
                for month, days in months.items():
                    for day, cost in days.items():
                        date = datetime(int(year), int(month), int(day)).date()
                        if current_date.replace(day=1) <= date <= (current_date.replace(day=1) + timedelta(days=32)).replace(day=1) - timedelta(days=1):
                            monthly_data[usage_type][current_date.strftime('%B-%Y')] += cost
        # Move to next month
        current_date = (current_date.replace(day=1) + timedelta(days=32)).replace(day=1)

    return monthly_data


@usage_bp.route('/', methods=['GET', 'POST'])
def index():
    min_date, max_date = get_date_range()

    # Fetch the list of services
    services = sorted(mongo_usage.db.list_collection_names())

    if request.method == 'POST':
        # Retrieve selected end date
        end_date = datetime.strptime(request.form['end_date'], '%Y-%m-%d').date()

        # Calculate the start date to ensure a continuous 7-day range
        start_date = end_date - timedelta(days=6)

        # Validate end date
        if end_date > datetime.utcnow().date() - timedelta(days=1):
            end_date = datetime.utcnow().date() - timedelta(days=1)

        # Convert dates to datetime objects
        start_date = datetime.combine(start_date, datetime.min.time())
        end_date = datetime.combine(end_date, datetime.max.time())

        # Query the database based on the selected date range and update service_data
        service_data = {}
        for service in services:
            data = list(mongo_usage.db[service].find())
            service_data[service] = []
            for i in range(7):
                date = start_date.date() + timedelta(days=i)
                total_cost = 0
                for doc in data:
                    year_data = doc.get(str(date.year), {})
                    month_data = year_data.get(str(date.month).zfill(2), {})
                    day_cost = month_data.get(str(date.day).zfill(2), 0)
                    total_cost += day_cost
                service_data[service].append(total_cost)
    else:
        # Default to showing data for the last 7 days
        end_date = max_date
        start_date = end_date - timedelta(days=6)

        # Convert dates to datetime objects
        start_date = datetime.combine(start_date, datetime.min.time())
        end_date = datetime.combine(end_date, datetime.max.time())

        # Query the database for the last 7 days' data
        service_data = {}
        for service in services:
            data = list(mongo_usage.db[service].find())
            service_data[service] = []
            for i in range(7):
                date = start_date.date() + timedelta(days=i)
                total_cost = 0
                for doc in data:
                    year_data = doc.get(str(date.year), {})
                    month_data = year_data.get(str(date.month).zfill(2), {})
                    day_cost = month_data.get(str(date.day).zfill(2), 0)
                    total_cost += day_cost
                service_data[service].append(total_cost)

    return render_template('usage.html', service_data=service_data, min_date=min_date, max_date=max_date, start_date=start_date, end_date=end_date, timedelta=timedelta)


@usage_bp.route('/usage-types/<service>', methods=['GET', 'POST'])
def usage(service):
    min_date, max_date = get_date_range()

    if request.method == 'POST':
        # Retrieve selected start and end dates
        # Retrieve selected end date
        end_date = datetime.strptime(request.form['end_date'], '%Y-%m-%d').date()

        # Calculate the start date to ensure a continuous 7-day range
        start_date = end_date - timedelta(days=6)

        # Validate end date
        if end_date > datetime.utcnow().date() - timedelta(days=1):
            end_date = datetime.utcnow().date() - timedelta(days=1)

        # Convert dates to datetime objects
        start_date = datetime.combine(start_date, datetime.min.time())
        end_date = datetime.combine(end_date, datetime.max.time())

    else:
        # Default to showing data for the last 7 days
        end_date = max_date
        start_date = end_date - timedelta(days=6)

        # Convert dates to datetime objects
        start_date = datetime.combine(start_date, datetime.min.time())
        end_date = datetime.combine(end_date, datetime.max.time())

    # Get usage data for the specified service
    usage_data = get_usage_data(service)

    return render_template('usage-types.html', service_name=service, usage_data=usage_data, min_date=min_date, max_date=max_date, start_date=start_date, end_date=end_date, timedelta=timedelta)


@usage_bp.route('/weekly_monthly/<service>', methods=['GET'])
def weekly_monthly(service):
    data_type = request.args.get('data_type')

    # Fetch the date range
    min_date, max_date = get_date_range()

aws_project/usage/templates/usage-types.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ service_name }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/usage-types.css') }}">
</head>
<body>
    <h1>{{ service_name }}</h1>

    <!-- Form for date selection -->
    <form action="/usage/usage-types/{{ service_name }}" method="POST" id="dateForm" onsubmit="return validateForm()">
        <label for="end_date">End Date:</label>
        <input type="date" id="end_date" name="end_date" min="{{ min_date }}" max="{{ max_date }}" value="{{ end_date }}">
        <input type="submit" value="Submit">
    </form>

    <!-- Back button to return to the service usage dashboard -->
    <div class="back-button">
        <a href="/usage/" class="button">Back to Service Usage</a>
    </div>

    <!-- Weekly and Monthly view buttons -->
    <div class="weekly-view-button">
        <a href="/usage/weekly_monthly/{{ service_name }}?data_type=weekly" class="button fixed-size-button">Weekly View</a>
    </div>

    <div class="monthly-view-button">
        <a href="/usage/weekly_monthly/{{ service_name }}?data_type=monthly" class="button fixed-size-button">Monthly View</a>
    </div>

    <!-- Note for the user -->
    <b2><strong>Note:</strong> It will automatically calculate Start date to show continuous 7 days data.</b2>

    <!-- Popup container -->
    <div class="popup-container" id="validateFormPopup">
        <p>Please select the end date.</p>
        <button onclick="closePopup('validateFormPopup')">Okay</button>
    </div>

    <script src="{{ url_for('static', filename='js/usage-types.js') }}"></script> 

    <!-- Table to display usage data -->
    <table>
        <thead>
            <tr>
                <th>Usage Type</th>
                <!-- Generate columns for the selected date range -->
                {% for i in range(7) %}
                    <th class="date">
                        {{ (start_date + timedelta(days=i)).strftime('%Y-%m-%d') }}
                        <br>
                        <button onclick="sortTable({{ loop.index0 }}, 'asc')">⬆️</button>
                        <button onclick="sortTable({{ loop.index0 }}, 'desc')">⬇️</button>
                    </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody id="usage-table-body">
            <!-- Loop through usage types -->
            {% for usage_type, data in usage_data.items() %}
            <tr>
                <td>{{ usage_type }}</td>
                <!-- Display data for each day -->
                {% for i in range(7) %}
                <td class="column-width">{{ data[(start_date + timedelta(days=i)).strftime('%Y-%m-%d')] | round(2) if data.get((start_date + timedelta(days=i)).strftime('%Y-%m-%d')) is not none else '0' }}</td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

aws_project/usage/templates/usage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service Usage</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/usage.css') }}">
</head>
<body>
    <h1>Service Usage</h1>
    <!-- Form for date selection -->
    <form action="/usage/" method="POST" id="dateForm" onsubmit="return validateForm()">
        <label for="end_date">End Date:</label>
        <input type="date" id="end_date" name="end_date" min="{{ min_date }}" max="{{ max_date }}" value="{{ end_date }}">
        <input type="submit" value="Submit">
    </form>

    <!-- Back button to return to the service dashboard -->
    <div class="back-button">
        <a href="/" class="button">Home</a>
    </div>

    <!-- Buttons to switch between weekly and monthly views -->
    <div class="weekly-button">
        <a href="/usage/weekly_monthly_index?data_type=weekly" class="button fixed-size-button">Weekly View</a>
    </div>
    
    <div class="monthly-button">
        <a href="/usage/weekly_monthly_index?data_type=monthly" class="button fixed-size-button">Monthly View</a>
    </div>

    <!-- Note for the user -->
    <b2><strong>Note:</strong> It will automatically calculate Start date to show continuous 7 days data.</b2>
    
    <!-- Popup container for empty end date -->
    <div class="popup-container" id="validateFormPopup">
        <p>Please select the end date.</p>
        <button onclick="closePopup('validateFormPopup')">Okay</button>
    </div>
    
    <script src="{{ url_for('static', filename='js/usage.js') }}"></script>      
    
    <!-- Table to display service usage data -->
    <table>
        <thead>
            <tr>
                <th>Services</th>
                <!-- Generate columns for the selected date range -->
                {% for i in range(7) %}
                    <th class="date">
                        {{ (start_date + timedelta(days=i)).strftime('%Y-%m-%d') }}
                        <br>
                        <button onclick="sortTable({{ loop.index0 }}, 'asc')">⬆️</button>
                        <button onclick="sortTable({{ loop.index0 }}, 'desc')">⬇️</button>
                    </th>
                {% endfor %}
                <th>Usage Types</th>
            </tr>
        </thead>
        <tbody id="service-table-body">
            <!-- Loop through service data -->
            {% for service, total_data in service_data.items() %}
            <tr>
                <td class="first-column">{{ service }}</td>
                <!-- Display total data for each day -->
                {% for data in total_data %}
                    <td>{{ data | round(2) }}</td>
                {% endfor %}
                <!-- Add view button -->
                <td><a href="{{ url_for('usage.usage', service=service) }}" class="view-button">View</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

aws_project/usage/templates/weekly_monthly.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ service_name }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/weekly_monthly.css') }}">
    <script src="{{ url_for('static', filename='js/weekly_monthly.js') }}"></script>
</head>
<body>
    <h1>{{ service_name }}</h1>

    <!-- Display a link to switch between weekly and monthly views -->
    {% if request.args.get('data_type') == 'monthly' %}
    <div class="back-button">
        <a href="/usage/weekly_monthly_index?data_type=monthly" class="button">Back to Service Usage</a>
    </div>
    {% elif request.args.get('data_type') == 'weekly' %}
    <div class="back-button">
        <a href="/usage/weekly_monthly_index?data_type=weekly" class="button">Back to Service Usage</a>
    </div>
    {% else %}
    <div class="back-button">
        <a href="/usage/weekly_monthly_index" class="button">Back to Service Usage</a>
    </div>
    {% endif %}

    <!-- Buttons to switch between weekly and monthly views -->
    <div class="daily-button">
        <a href="/usage/usage-types/{{ service_name }}" class="button fixed-size-button">Daily View</a>
    </div>

    {% if request.args.get('data_type') == 'monthly' %}
    <div class="weekly-button">
        <a href="/usage/weekly_monthly/{{ service_name }}?data_type=weekly" class="button fixed-size-button">Weekly View</a>
    </div>
    {% else %}
    <div class="monthly-button">
        <a href="/usage/weekly_monthly/{{ service_name }}?data_type=monthly" class="button fixed-size-button">Monthly View</a>
    </div>
    {% endif %}

    <!-- Table to display weekly or monthly usage data -->
    <table>
        <thead>
            <tr>
                <th>Usage Type</th>
                <!-- Generate columns for the latest 8 weeks or months -->
                {% for label in labels %}
                    <th>
                        {{ label }}
                        <br>
                        <button onclick="sortTable({{ loop.index0 }}, 'asc')">⬆️</button>
                        <button onclick="sortTable({{ loop.index0 }}, 'desc')">⬇️</button>
                    </th>
                {% endfor %}
            </tr>
        </thead>
        <tbody id="usage-table-body">
            <!-- Loop through each date -->
            {% for date, usage_data in usage_data.items() %}
                <tr>
                    <td>{{ date }}</td>
                    <!-- Display total data for each usage type -->
                    {% for usage_type, value in usage_data.items() %}
                        <td class="column-width"> {{ '%.2f' % value if value is not none else '0' }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

aws_project/usage/templates/weekly_monthly_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Service Usage</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/weekly_monthly_index.css') }}">
    <script src="{{ url_for('static', filename='js/weekly_monthly_index.js') }}"></script>
</head>
<body>
    <h1>Service Usage</h1>

    <!-- Display a link to switch between weekly and monthly views -->
    <div class="back-button">
        <a href="/" class="button">Home</a>
    </div>

    <!-- Buttons to switch between weekly and monthly views -->
    <div class="daily-button">
        <a href="/usage/" class="button fixed-size-button">Daily View</a>
    </div>
    
    {% if request.args.get('data_type') == 'monthly' %}
    <div class="weekly-button">
        <a href="/usage/weekly_monthly_index?data_type=weekly" class="button fixed-size-button">Weekly View</a>
    </div>
    {% else %}
    <div class="monthly-button">
        <a href="/usage/weekly_monthly_index?data_type=monthly" class="button fixed-size-button">Monthly View</a>
    </div>
    {% endif %}

    <!-- Table to display weekly or monthly usage data -->
    <table>
        <thead>
            <tr>
                <th>Services</th>
                <!-- Generate columns for the latest 8 weeks or months -->
                {% for label in labels %}
                    {% if request.args.get('data_type') == 'monthly' %}
                        <th class="th1 no-wrap {{ 'fixed-width' if loop.index < 9 else '' }}">
                    {% else %}
                        <th class="{{ 'fixed-width' if loop.index < 9 else '' }}">
                    {% endif %}
                        {{ label }}
                        <br>
                        <button onclick="sortTable({{ loop.index0 }}, 'asc')">⬆️</button>
                        <button onclick="sortTable({{ loop.index0 }}, 'desc')">⬇️</button>
                    </th>
                {% endfor %}
                <th>Usage Types</th>
            </tr>
        </thead>
        <tbody id="service-table-body">
            <!-- Loop through each date -->
            {% for date, usage_data in usage_data.items() %}
                <tr>
                    <td class="first-column">{{ date }}</td>
                    <!-- Display total data for each usage type -->
                    {% for usage_type, value in usage_data.items() %}
                        <td>{{ '%.2f' % value if value is not none else '0' }}</td>
                    {% endfor %}
                    <!-- Add view button with conditional redirection -->
                    <td>
                        {% if request.args.get('data_type') == 'monthly' %}
                            <a href="{{ url_for('usage.weekly_monthly', service=date, data_type='monthly') }}" class="view-button">View</a>
                        {% else %}
                            <a href="{{ url_for('usage.weekly_monthly', service=date, data_type='weekly') }}" class="view-button">View</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>