aws_project/alert/__init__.py
from flask import Blueprint

alert_bp = Blueprint('alert', __name__, template_folder='templates')

from . import routes

aws_project/usage/routes.py
from flask import Blueprint, render_template, request
from flask_pymongo import PyMongo
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from . import usage_bp

from flask_caching import Cache
from hashlib import md5

def make_cache_key():
    return md5(request.path.encode('utf-8')).hexdigest()

cache = Cache()

# Initialize cache with default settings
def init_cache(app):
    cache.init_app(app)

usage_bp = Blueprint('usage', __name__, template_folder='templates')

# Use the usage MongoDB instance
mongo_usage = PyMongo()

@usage_bp.record_once
def on_load(state):
    global mongo_usage
    mongo_usage.init_app(state.app, uri=state.app.config["MONGO_URI_USAGE"])

# Function to get date range
def get_date_range():
    min_date = datetime.utcnow().date()
    max_date = datetime(1970, 1, 1).date()  # start with a very old date

    for collection in mongo_usage.db.list_collection_names():
        data = list(mongo_usage.db[collection].find())
        for document in data:
            for year, months in document.items():
                if not year.isdigit():
                    continue
                for month, days in months.items():
                    for day in days.keys():
                        date = datetime(int(year), int(month), int(day)).date()
                        min_date = min(min_date, date)
                        max_date = max(max_date, date)

    return min_date, max_date


def get_usage_data(service):
    # Query the database for the specified service
    data = list(mongo_usage.db[service].find())

    # Initialize an empty dictionary to store the usage data
    usage_data = {}

    # Loop through the data and populate the usage_data dictionary
    for doc in data:
        for year, months in doc.items():
            if not year.isdigit():
                continue
            for month, days in months.items():
                for day, cost in days.items():
                    date = f"{year}-{month}-{day}"
                    usage_type = doc.get('UsageTypes')
                    if usage_type not in usage_data:
                        usage_data[usage_type] = {}
                    usage_data[usage_type][date] = float(cost)

    return usage_data


# Function to calculate weekly usage data
@cache.cached(timeout=86400, key_prefix=make_cache_key)  # Cache for 24 hours (adjust timeout as needed)
def calculate_weekly_data(service):
    # Query the database for the specified service
    data = list(mongo_usage.db[service].find())

    # Initialize weekly data dictionary
    weekly_data = {}

    min_date, max_date = get_date_range()
    # Calculate start and end dates for the past 8 weeks (including the current week)
    # end_date = max_date
    end_date = max_date - timedelta(days=(max_date.weekday() + 1) % 7)
    start_date = end_date - relativedelta(weeks=7)

    # Find the Monday of the start_date week
    start_date -= timedelta(days=start_date.weekday())

    # Iterate over each week within the selected date range
    current_date = start_date
    while current_date <= end_date:
        for doc in data:
            usage_type = doc.get('UsageTypes')
            if usage_type not in weekly_data:
                weekly_data[usage_type] = {}
            weekly_data[usage_type][current_date] = 0
            for year, months in doc.items():
                if not year.isdigit():
                    continue
                for month, days in months.items():
                    for day, cost in days.items():
                        date = datetime(int(year), int(month), int(day)).date()
                        if current_date <= date < current_date + timedelta(days=7):
                            weekly_data[usage_type][current_date] += cost
        # Move to next week
        current_date += timedelta(days=7)

    return weekly_data


# Function to calculate monthly usage data
@cache.cached(timeout=86400)  # Cache for 24 hours (adjust timeout as needed)
def calculate_monthly_data(service):
    # Query the database for the specified service
    data = list(mongo_usage.db[service].find())

    # Initialize monthly data dictionary
    monthly_data = {}

    # Fetch the date range
    min_date, max_date = get_date_range()

    # Calculate start and end dates for the past 8 months (including the current month)
    # end_date = max_date.replace(day=1)
    end_date = max_date.replace(day=1) - timedelta(days=1)
    start_date = end_date.replace(day=1) - relativedelta(months=7)

    # Iterate over each month within the selected date range
    current_date = start_date.replace(day=1)
    while current_date.replace(day=1) <= end_date.replace(day=1):
        for doc in data:
            usage_type = doc.get('UsageTypes')
            if usage_type not in monthly_data:
                monthly_data[usage_type] = {}
            monthly_data[usage_type][current_date.strftime('%B-%Y')] = 0
            for year, months in doc.items():
                if not year.isdigit():
                    continue
                for month, days in months.items():
                    for day, cost in days.items():
                        date = datetime(int(year), int(month), int(day)).date()
                        if current_date.replace(day=1) <= date <= (current_date.replace(day=1) + timedelta(days=32)).replace(day=1) - timedelta(days=1):
                            monthly_data[usage_type][current_date.strftime('%B-%Y')] += cost
        # Move to next month
        current_date = (current_date.replace(day=1) + timedelta(days=32)).replace(day=1)

    return monthly_data


@usage_bp.route('/', methods=['GET', 'POST'])
def index():
    min_date, max_date = get_date_range()

    # Fetch the list of services
    services = sorted(mongo_usage.db.list_collection_names())

    if request.method == 'POST':
        # Retrieve selected end date
        end_date = datetime.strptime(request.form['end_date'], '%Y-%m-%d').date()

        # Calculate the start date to ensure a continuous 7-day range
        start_date = end_date - timedelta(days=6)

        # Validate end date
        if end_date > datetime.utcnow().date() - timedelta(days=1):
            end_date = datetime.utcnow().date() - timedelta(days=1)

        # Convert dates to datetime objects
        start_date = datetime.combine(start_date, datetime.min.time())
        end_date = datetime.combine(end_date, datetime.max.time())

        # Query the database based on the selected date range and update service_data
        service_data = {}
        for service in services:
            data = list(mongo_usage.db[service].find())
            service_data[service] = []
            for i in range(7):
                date = start_date.date() + timedelta(days=i)
                total_cost = 0
                for doc in data:
                    year_data = doc.get(str(date.year), {})
                    month_data = year_data.get(str(date.month).zfill(2), {})
                    day_cost = month_data.get(str(date.day).zfill(2), 0)
                    total_cost += day_cost
                service_data[service].append(total_cost)
    else:
        # Default to showing data for the last 7 days
        end_date = max_date
        start_date = end_date - timedelta(days=6)

        # Convert dates to datetime objects
        start_date = datetime.combine(start_date, datetime.min.time())
        end_date = datetime.combine(end_date, datetime.max.time())

        # Query the database for the last 7 days' data
        service_data = {}
        for service in services:
            data = list(mongo_usage.db[service].find())
            service_data[service] = []
            for i in range(7):
                date = start_date.date() + timedelta(days=i)
                total_cost = 0
                for doc in data:
                    year_data = doc.get(str(date.year), {})
                    month_data = year_data.get(str(date.month).zfill(2), {})
                    day_cost = month_data.get(str(date.day).zfill(2), 0)
                    total_cost += day_cost
                service_data[service].append(total_cost)

    return render_template('usage.html', service_data=service_data, min_date=min_date, max_date=max_date, start_date=start_date, end_date=end_date, timedelta=timedelta)


@usage_bp.route('/usage-types/<service>', methods=['GET', 'POST'])
def usage(service):
    min_date, max_date = get_date_range()

    if request.method == 'POST':
        # Retrieve selected start and end dates
        # Retrieve selected end date
        end_date = datetime.strptime(request.form['end_date'], '%Y-%m-%d').date()

        # Calculate the start date to ensure a continuous 7-day range
        start_date = end_date - timedelta(days=6)

        # Validate end date
        if end_date > datetime.utcnow().date() - timedelta(days=1):
            end_date = datetime.utcnow().date() - timedelta(days=1)

        # Convert dates to datetime objects
        start_date = datetime.combine(start_date, datetime.min.time())
        end_date = datetime.combine(end_date, datetime.max.time())

    else:
        # Default to showing data for the last 7 days
        end_date = max_date
        start_date = end_date - timedelta(days=6)

        # Convert dates to datetime objects
        start_date = datetime.combine(start_date, datetime.min.time())
        end_date = datetime.combine(end_date, datetime.max.time())

    # Get usage data for the specified service
    usage_data = get_usage_data(service)

    return render_template('usage-types.html', service_name=service, usage_data=usage_data, min_date=min_date, max_date=max_date, start_date=start_date, end_date=end_date, timedelta=timedelta)


@usage_bp.route('/weekly_monthly/<service>', methods=['GET'])
def weekly_monthly(service):
    data_type = request.args.get('data_type')

    # Fetch the date range
    min_date, max_date = get_date_range()

aws_project/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Combined Application</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
</head>
<body>
    <div class="ticker-container">
        <div class="ticker-wrap">
            {% for service, (cost, direction, change) in top_services.items() %}
                <div class="ticker-item">{{ service }} {{ cost }}
                    {% if direction == 'up' %}
                        <span class="up">▲ {{ change }}%</span>
                    {% elif direction == 'down' %}
                        <span class="down">▼ {{ change }}%</span>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
    
    <div class="sidebar">
        <h1>Welcome, Beni</h1>
        <ul>
            <li><a href="{{ url_for('usage.index') }}" class="button">Usage Application</a></li>
            <li><a href="{{ url_for('alert.index') }}" class="button">Alert Application</a></li>
            <li><a class="button">Cron Job : 
                <label class="switch">
                    <input class="switch-input" type="checkbox" id="cron-toggle" onchange="toggleCron()" {% if cron_enabled %}checked{% endif %} />
                    <span class="switch-label" data-on="On" data-off="Off"></span>
                    <span class="switch-handle"></span>
                </label>
            </a></li>
        </ul>
    </div>
    <div class="main-content">
        <div class="top-section">
            <div>
                <h2>Totals Services</h2>
                <p>{{ num_services }}</p>
            </div>
            <div>
                <h2>Curr. Month's Cost</h2>
                <p>{{ total_current_month_cost }} (till {{ current_date }})</p>
            </div>
            <div>
                <h2>Last Month's Cost</h2>
                <p>{{ total_last_month_cost }}</p>
            </div>
            <div>
                <h2>AWS Account ID</h2>
                <p>{{ aws_account_id }}</p>
            </div>
            <div>
                <h2>Regions Used</h2>
                <p>{{ regions_used }}</p>
            </div>
        </div>

        <h2>Daily Data: Cost Trend of Top 5 Services Over Last 7 Days</h2>
        <div id="controlsContainer">
            <div id="graphTypeToggleContainer">
                <label class="graph-switch">
                    <input type="checkbox" id="graphTypeToggle" onchange="updateGraphType()">
                    <span class="graph-switch-label" data-on="Line" data-off="Bar"></span>
                    <span class="graph-switch-handle"></span>
                </label>
            </div>
            <!-- Add the dropdown menu for selecting services -->
            <div id="serviceSelectContainer">
                <label for="serviceSelect">Select Service:</label>
                <select id="serviceSelect" onchange="updateService()">
                    <!-- Options will be populated dynamically -->
                </select>
            </div>
        </div>

        <div class="graph-grid">
            <div class="graph">
                <canvas id="dailyGraph1"></canvas>
            </div>
            <div class="graph">
                <canvas id="dailyGraph2"></canvas>
            </div>
        </div>

        <h2>Weekly Data: Cost Trend of Top 5 Services Over Last 4 Weeks</h2>
        <div id="weeklyControlsContainer">
            <div id="weeklyGraphTypeToggleContainer">
                <label class="graph-switch">
                    <input type="checkbox" id="weeklyGraphTypeToggle" onchange="updateWeeklyGraphType()">
                    <span class="graph-switch-label" data-on="Line" data-off="Bar"></span>
                    <span class="graph-switch-handle"></span>
                </label>
            </div>
            <!-- Add the dropdown menu for selecting services -->
            <div id="weeklyServiceSelectContainer">
                <label for="weeklyServiceSelect">Select Service:</label>
                <select id="weeklyServiceSelect" onchange="updateWeeklyService()">
                    <!-- Options will be populated dynamically -->
                </select>
            </div>
        </div>

        <div class="graph-grid">
            <div class="graph">
                <canvas id="weeklyGraph1"></canvas>
            </div>
            <div class="graph">
                <canvas id="weeklyGraph2"></canvas>
            </div>
        </div>

        <!-- Monthly Data Section -->
        <h2>Monthly Data: Cost Trend of Top 5 Services Over Last 4 Months</h2>
        <div id="monthlyControlsContainer">
            <div id="monthlyGraphTypeToggleContainer">
                <label class="graph-switch">
                    <input type="checkbox" id="monthlyGraphTypeToggle" onchange="updateMonthlyGraphType()">
                    <span class="graph-switch-label" data-on="Line" data-off="Bar"></span>
                    <span class="graph-switch-handle"></span>
                </label>
            </div>
            <!-- Add the dropdown menu for selecting services -->
            <div id="monthlyServiceSelectContainer">
                <label for="monthlyServiceSelect">Select Service:</label>
                <select id="monthlyServiceSelect" onchange="updateMonthlyService()">
                    <!-- Options will be populated dynamically -->
                </select>
            </div>
        </div>

        <div class="graph-grid">
            <div class="graph">
                <canvas id="monthlyGraph1"></canvas>
            </div>
            <div class="graph">
                <canvas id="monthlyGraph2"></canvas>
            </div>
        </div>
    </div>

    <!-- Include Chart.js library -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
</body>
</html>